### PR TITLE
Style changes

### PR DESCRIPTION
**Pull request by OSP123**
Hey Lucas,

I made the changes to the accounts/profile/ page (entrys_panel) to make it responsive on devices with a width of < 640px.

### CODE REVIEW

**Comment by lucasmarcelli** [comment]
Nice I'll take a look tomorrow!

**Comment by OSP123** [comment]
Thanks man

**Comment by lucasmarcelli** [comment]
Looks good, I can't actually test it yet because I'm not at home till tonight but I dont see any problems in the code. Once I look at it tested I'll pull it in and deploy it!

**Comment by OSP123** [comment]
Sounds good :). Yeah, it shouldn&#39;t have any effect on functionality, since it&#39;s just changes in CSS and some CSS classes in the html.

**Comment by lucasmarcelli** [comment]
Nice. It's live! I like it thanks so much dude.

**Comment by OSP123** [comment]
Cool, no worries :).

**Pull request merged**
